### ISSUE TITLE
Setting metadata is not possible due to resource.update_acl_cdmi missing

### ISSUE THREAD

**Issue by alahiff** [radon-provenance/radon-web#2]
I tried to set metadata using `radon meta set` however `radon meta ls` always returns nothing. 

Looking at the radon-web logs, there is an Internal Server Error caused by:
```  
File "/code/radon-web/rest_cdmi/views.py", line 399, in put
    return self.put_data_object(path)
  File "/code/radon-web/rest_cdmi/views.py", line 1061, in put_data_object
    return self.put_data_object_cdmi(parent, name, resource)
  File "/code/radon-web/rest_cdmi/views.py", line 981, in put_data_object_cdmi
    resource.update_acl_cdmi(cdmi_acl)
AttributeError: 'Resource' object has no attribute 'update_acl_cdmi'
```

The CLI returns no errors in this situation because it only checks for http response codes 400, 401, 403, 404, 406, and 409 and assumes that everything else (including 500) is a success.

**Comment by alahiff** [comment]
I found that I can workaround this issue by adding a new line before https://github.com/radon-provenance/radon-web/blob/1.0.1/rest_cdmi/views.py#L981, i.e.
```
            resource.update_acl_cdmi(cdmi_acl)
```
becomes:
```
        if cdmi_acl:
            resource.update_acl_cdmi(cdmi_acl)
```
This works because if you just try to set metadata using the CLI `cdmi_acl` is defined but is an empty list. In this case there's no need to try to update ACLs because none are defined. This fixes my problem, but the missing definition of `resource.update_acl_cdmi` still needs to be sorted out.

**Comment by JeromeFuselier** [comment]
I've added the missing functions that disappeared at some point. This will work in the next release (1.0.2)
